// <auto-generated />
namespace TheNuggetList.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddNuggetsAndMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNuggetsAndMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201306062142212_AddNuggetsAndMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
